#!/opt/homebrew/bin/bash

cmd + alt - 1 : yabai -m display --focus 1
cmd + alt - 2 : yabai -m display --focus 2
cmd + alt - 3 : yabai -m display --focus 3
cmd + alt - 4 : yabai -m display --focus 4
cmd + alt - 5 : yabai -m display --focus 5
cmd + alt - 6 : yabai -m display --focus 6
cmd + alt - 7 : yabai -m display --focus 7
cmd + alt - 8 : yabai -m display --focus 8
cmd + alt - 9 : yabai -m display --focus 9
cmd + alt - 0 : yabai -m display --focus 10

# cmd - 1 : yabai -m space --focus 1
# cmd - 2 : yabai -m space --focus 2
# cmd - 3 : yabai -m space --focus 3
# cmd - 4 : yabai -m space --focus 4
# cmd - 5 : yabai -m space --focus 5
# cmd - 6 : yabai -m space --focus 6
# cmd - 7 : yabai -m space --focus 7
# cmd - 8 : yabai -m space --focus 8
# cmd - 9 : yabai -m space --focus 9
# cmd - 0 : yabai -m space --focus 10
cmd - 1 : ${HOME}/.config/skhd/focus_space.sh 1
cmd - 2 : ${HOME}/.config/skhd/focus_space.sh 2
cmd - 3 : ${HOME}/.config/skhd/focus_space.sh 3
cmd - 4 : ${HOME}/.config/skhd/focus_space.sh 4
cmd - 5 : ${HOME}/.config/skhd/focus_space.sh 5
cmd - 6 : ${HOME}/.config/skhd/focus_space.sh 6
cmd - 7 : ${HOME}/.config/skhd/focus_space.sh 7
cmd - 8 : ${HOME}/.config/skhd/focus_space.sh 8
cmd - 9 : ${HOME}/.config/skhd/focus_space.sh 9
cmd - 0 : ${HOME}/.config/skhd/focus_space.sh 10

cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

cmd + shift - h : yabai -m window --swap west
cmd + shift - j : yabai -m window --swap south
cmd + shift - k : yabai -m window --swap north
cmd + shift - l : yabai -m window --swap east

cmd - u : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
cmd - i : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
cmd - o : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
cmd - p : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# cmd + shift - 1 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 1 && yabai -m space --focus 1 && yabai -m window --focus "$target"
# cmd + shift - 2 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 2 && yabai -m space --focus 2 && yabai -m window --focus "$target"
# cmd + shift - 3 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 3 && yabai -m space --focus 3 && yabai -m window --focus "$target"
# cmd + shift - 4 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 4 && yabai -m space --focus 4 && yabai -m window --focus "$target"
# cmd + shift - 5 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 5 && yabai -m space --focus 5 && yabai -m window --focus "$target"
# cmd + shift - 6 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 6 && yabai -m space --focus 6 && yabai -m window --focus "$target"
# cmd + shift - 7 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 7 && yabai -m space --focus 7 && yabai -m window --focus "$target"
# cmd + shift - 8 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 8 && yabai -m space --focus 8 && yabai -m window --focus "$target"
# cmd + shift - 9 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 9 && yabai -m space --focus 9 && yabai -m window --focus "$target"
# cmd + shift - 0 : target="$(yabai -m query --windows --window | jq .id)" && yabai -m window --space 10 && yabai -m space --focus 10 && yabai -m window --focus "$target"

cmd + shift - 1 : ${HOME}/.config/skhd/move_to_space.sh 1
cmd + shift - 2 : ${HOME}/.config/skhd/move_to_space.sh 2
cmd + shift - 3 : ${HOME}/.config/skhd/move_to_space.sh 3
cmd + shift - 4 : ${HOME}/.config/skhd/move_to_space.sh 4
cmd + shift - 5 : ${HOME}/.config/skhd/move_to_space.sh 5
cmd + shift - 6 : ${HOME}/.config/skhd/move_to_space.sh 6
cmd + shift - 7 : ${HOME}/.config/skhd/move_to_space.sh 7
cmd + shift - 8 : ${HOME}/.config/skhd/move_to_space.sh 8
cmd + shift - 9 : ${HOME}/.config/skhd/move_to_space.sh 9
cmd + shift - 0 : ${HOME}/.config/skhd/move_to_space.sh 10

cmd + alt + shift - 1 : ${HOME}/.config/skhd/send_to_display.sh 1
cmd + alt + shift - 2 : ${HOME}/.config/skhd/send_to_display.sh 2
cmd + alt + shift - 3 : ${HOME}/.config/skhd/send_to_display.sh 3
cmd + alt + shift - 4 : ${HOME}/.config/skhd/send_to_display.sh 4
cmd + alt + shift - 5 : ${HOME}/.config/skhd/send_to_display.sh 5
cmd + alt + shift - 6 : ${HOME}/.config/skhd/send_to_display.sh 6
cmd + alt + shift - 7 : ${HOME}/.config/skhd/send_to_display.sh 7
cmd + alt + shift - 8 : ${HOME}/.config/skhd/send_to_display.sh 8
cmd + alt + shift - 9 : ${HOME}/.config/skhd/send_to_display.sh 9
cmd + alt + shift - 0 : ${HOME}/.config/skhd/send_to_display.sh 10

cmd + shift - space : yabai -m window --toggle float
cmd + shift - f : yabai -m window --toggle zoom-fullscreen

cmd - q : ${HOME}/.config/skhd/quit_on_last.sh

ctrl - t: open -n /Applications/Ghostty.app
