#!/opt/homebrew/bin/bash

cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0 : yabai -m space --focus 10

# cmd - h : yabai -m window --focus west
# cmd - j : yabai -m window --focus south
# cmd - k : yabai -m window --focus north
# cmd - l : yabai -m window --focus east
# Sometimes Orion doesn't focus the window correctly, so we need to focus it twice
cmd - h : target="$(yabai -m query --windows --window west | jq .id)" && yabai -m window --focus "$target" && sleep 0.05 && yabai -m window --focus "$target"
cmd - j : target="$(yabai -m query --windows --window south | jq .id)" && yabai -m window --focus "$target" && sleep 0.05 && yabai -m window --focus "$target"
cmd - k : target="$(yabai -m query --windows --window north | jq .id)" && yabai -m window --focus "$target" && sleep 0.05 && yabai -m window --focus "$target"
cmd - l : target="$(yabai -m query --windows --window east | jq .id)" && yabai -m window --focus "$target" && sleep 0.05 && yabai -m window --focus "$target"

cmd + shift - h : yabai -m window --swap west
cmd + shift - j : yabai -m window --swap south
cmd + shift - k : yabai -m window --swap north
cmd + shift - l : yabai -m window --swap east

cmd - u : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
cmd - i : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
cmd - o : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
cmd - p : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

cmd + shift - 1 : yabai -m window --space 1 && yabai -m space --focus 1
cmd + shift - 2 : yabai -m window --space 2 && yabai -m space --focus 2
cmd + shift - 3 : yabai -m window --space 3 && yabai -m space --focus 3
cmd + shift - 4 : yabai -m window --space 4 && yabai -m space --focus 4
cmd + shift - 5 : yabai -m window --space 5 && yabai -m space --focus 5
cmd + shift - 6 : yabai -m window --space 6 && yabai -m space --focus 6
cmd + shift - 7 : yabai -m window --space 7 && yabai -m space --focus 7
cmd + shift - 8 : yabai -m window --space 8 && yabai -m space --focus 8
cmd + shift - 9 : yabai -m window --space 9 && yabai -m space --focus 9
cmd + shift - 0 : yabai -m window --space 10 && yabai -m space --focus 10

# cmd - q : $HOME/.config/skhd/quit_if_last.sh
# alt - q : yabai -m window --close

cmd + shift - space : yabai -m window --toggle float
